### ISSUE TITLE
Why localization network pick the middle when multiple objects is presented?

### ISSUE THREAD

**Issue by ermolenkodev** [learnml-today/object-detection-with-pytorch#11]
Intuitively it's reasonable but I can't fully understand why it's the case. Can you add some hints or give me some additional links?

**Comment by creotiv** [comment]
Imagine that you are a goalkeeper, and you need to catch the ball, but the football goal is so big that you physically cant catch it all the time, so you pick place somewhere in the middle (if balls is uniformly distributed).
Also, you are training solution with only part of the data, that's mean that one example move weights to better catch the ball in the left corner, then come to another example and move weights to better catch the ball in the right corner, and you end with some mean result in the center.

**Comment by ermolenkodev** [comment]
Thanks)
