### ISSUE TITLE
SSD priors

### ISSUE THREAD

**Issue by Nazarko12345** [learnml-today/object-detection-with-pytorch#14]
- In `class DefaultBoxes(object): `  why u set `# for aspect 1 adding additional box
            sk = sqrt(sk*sk+1)` sk should be sqrt(sk*next_sk)
- Also i think we need `        self.dboxes_ltrb = self.dboxes.clone()
`clamp it to (0,1) as well
- And here `def encode(self, bboxes, labels_in, criteria = 0.5, num_classes=21):
        ious = calc_iou_tensor(bboxes, self.dboxes)` 
self.dboxes is in coordinate(xc,yc,w,h) ? but we need x1,y1,x2,y2?

**Comment by creotiv** [comment]
1) yes. fixed this in Colab. Thanks  for a quick eye)
2) we already clamped it line above self.dboxes.clamp_(min=0, max=1) - this is inplace operation.
3) yes, but we set dboxes in encode  to self.dboxes = dboxes(order="ltrb"), so it in x1,y1,x2,y2 format already.

**Comment by Nazarko12345** [comment]
2. `self.dboxes_ltrb[:, 0] = self.dboxes[:, 0] - 0.5 * self.dboxes[:, 2]
        self.dboxes_ltrb[:, 1] = self.dboxes[:, 1] - 0.5 * self.dboxes[:, 3]
        self.dboxes_ltrb[:, 2] = self.dboxes[:, 0] + 0.5 * self.dboxes[:, 2]
        self.dboxes_ltrb[:, 3] = self.dboxes[:, 1] + 0.5 * self.dboxes[:, 3]`
After it i think we should add clamp because i get values more than 1 and less then 0
3.Oh sorry see it )

**Comment by creotiv** [comment]
2. you are right, this happens because of some dboxes out of image shape, so when we transform them into ltrb format we get out [0,1] values.

**Comment by Nazarko12345** [comment]
ok thanks
