### ISSUE TITLE
Scale(Variance) in SSD

### ISSUE THREAD

**Issue by Nazarko12345** [learnml-today/object-detection-with-pytorch#15]
```
Coordinates relativnes calculated like this:

xy=(xy−default_boxes_xy)/(scale_xy∗default_boxes_wh) 

wh=loge(wh/default_boxes_wh)/scale_wh 

To decode just revert operations in encoding for coordinates.
```
Whats the point of normalizing values by scale_wh,scale_xy?If im right we normalize by default_boxes_wh to equally penalize small and large boxes so why you also divide by scales i dont understand.

**Comment by creotiv** [comment]
there are 2 problems that we are trying to fix:
1) we should handle small and big boxes with ~ the same penalty.
Here we using offset and log for wh, thus minimizing big|small difference.

2) we should handle human error on dboxes. Basically, we have for example object car, and on some photo, bbox is little moved to left, on the next to the right, so we have some deviation.
This is how I see it, cause I didn't find any information on the internet, except that this is improving the performance of the network.
Here we use scale_xy, scale_wh to eliminate standard deviation (why someone called it variance I don't know). The same scaling is used in the faster rcnn and mask rcnn networks, and also I didn't find any mentions on how they got this.

there is a good article on box encoding, that I recommend you to read, it may give some explanation https://leimao.github.io/blog/Bounding-Box-Encoding-Decoding/
