### ISSUE TITLE
After RPN to ROI Align

### ISSUE THREAD

**Issue by Nazarko12345** [learnml-today/object-detection-with-pytorch#17]
After RPN we generate anchor boxes.Then finding best ious with boxes and anchors.Then  RPN predict boxes and confidence for positive and negative examples.After RPN we take best anchors  from different scales and then resizing them to same size using ROI Align and then classificate them ?Im like dont understand what the point of ROI Align if we can classificate from RPN prediction like that was in SSD instead of finding confidence ?

**Comment by creotiv** [comment]
RPN gives us proposals with some confidence, then we map these proposals to our training targets, not anchors.
In SSD we have fixed input like 300px, 500px, that gives us fixed feature size for all images. Here we don't change spatial proportions of images and give big variability in shape sizes. Thus we need to fix the size of features somewhere inside the network, in other cases, we will need many more layers to handle all this data. Also, we using Fully Connected layers which have static spatial size. Of course, we can use Conv1x1 layers instead, but that not the same, fully connected works better.

**Comment by creotiv** [comment]
Model is just a statistic, so when you have more variability you need a bigger model. 
for example, you are using conv 3x3 layer with 5 filters and run it on spatial size 10x10. On such size you can catch corners, eyes, etc, pretty big objects. But if you change the spatial size to 500x500 it will not be able to handle the same objects instead it will handle some pixel artifacts.

**Comment by Nazarko12345** [comment]
Im cant undestand to what boxes we apply ROI Align

**Comment by creotiv** [comment]
That's why you need to control spatial resolution of your inputs

**Comment by Nazarko12345** [comment]
To prediction of our RPN?

**Comment by creotiv** [comment]
We apply ROI Align to our proposals. it basically cut off our proposed ROI from feature and then resize it to needed shape

**Comment by creotiv** [comment]
yes

**Comment by creotiv** [comment]
input->rpn->proposals->roi-align->detector

**Comment by Nazarko12345** [comment]
Oh ok
