### ISSUE TITLE
OSError in Google Colab

### ISSUE THREAD

**Issue by ConfuzedCoder** [learnml-today/object-detection-with-pytorch#2]
Hi

I am getting OSError while running the notebook in Google Colab. But it's working on my local system. 

![image](https://user-images.githubusercontent.com/15157792/69337037-ecb9ba80-0c85-11ea-86c3-d2492d4ebdc1.png)

**Comment by creotiv** [comment]
@tandelDipak yes this happens sometimes in collab when unzipping files. I think some problems with synchronization data on disk. Just restart your runtime (Ctrl+M) and rerun from python import statements (no need to reinstall with pip and reuploading data)

**Comment by ConfuzedCoder** [comment]
@creotiv  Thanks. It worked.
