### ISSUE TITLE
Absent masks in proposed dataset for home task in lecture #2

### ISSUE THREAD

**Issue by dhrebeniuk** [learnml-today/object-detection-with-pytorch#23]
There is in 2nd lecture proposed dataset by link http://www.vision.caltech.edu/visipedia/CUB-200-2011.html .

Home task requires create model for detection position of boxes and model for mask detection as described in lecture.

But, there are just boxes present in this dataset(Boxes for birds and theirs parts).
Masks images absent in this dataset :(.

**Comment by creotiv** [comment]
There is segmentation link with masks in the download section on the site
