### ISSUE TITLE
Understanding PyTorch Resnet implementation

### ISSUE THREAD

**Issue by ConfuzedCoder** [learnml-today/object-detection-with-pytorch#5]
Hi
I am not able to understand what goes in and what comes out from line number 68 in the  [PyTorch Resnet](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py) implementation.  downsample is an attribute of the class (line number 54)  then why it's called like method or function. What does it do?

It's not part of the course but I am learning it to improve my PyTorch skills. It will help me in implemenation.

**Comment by creotiv** [comment]
if you see in PyTorch something like method|function(tensor) then this is Module class (layer).
So here downsample is just a layer that used for downsampling, and it set in the __init__ of the class.

Here you can see setting the downsample layer https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L181

**Comment by creotiv** [comment]
So PyTorch has 3 basic things is a Module, Sequential(which also a Module) and function. that's all.
