### ISSUE TITLE
additional layers to improve memory of the network

### ISSUE THREAD

**Issue by ermolenkodev** [learnml-today/object-detection-with-pytorch#6]
What is the intuition behind the comment in the second lecture?
`# add some additional layers to improve memory of the network`
I usually think of adding new layers as a way to allow the network to learn more abstract representations.

**Comment by creotiv** [comment]
every new layer that you add is additional data that network capable to save inside it weights. So when you adding layers you also increasing the "memory" of the network.
As for abstraction, it depends on type of layers. For example, Conv with kernel 1x1 will not give you abstraction but will give you dimensionality reduction (many people confuse them with fully connected layers, but that's not the same)

**Comment by ermolenkodev** [comment]
Thanks
