### ISSUE TITLE
iou metric

### ISSUE THREAD

**Issue by ermolenkodev** [learnml-today/object-detection-with-pytorch#7]
Can you please explain this remark from the second lecture?
> The only thing that you should always remember is that your prediction depends on the quality dataset markup. If markup not very accurate, then you should push your network to give bigger IoU results.

Don’t we always aim to increase the IOU metric regardless of the dataset?

**Comment by creotiv** [comment]
What i mean is that if dataset bboxes IoU with objects is shit, then making network to be strict with it will mean that you train it to make bad bbox prediction.
In such cases, of course, it's better to re-label dataset or find a good one, but if its not possible then adding some random to your bbox prediction will help the network to find a better prediction.

**Comment by ermolenkodev** [comment]
Ok, I got it, thank you
