### ISSUE TITLE
question on inference in Yolo from Akash Prakash

### ISSUE THREAD

**Issue by creotiv** [learnml-today/object-detection-with-pytorch#8]
hello, i have a doubt
labels = res[:,:,boxes*5:].repeat((1,1,boxes)).view(-1,1)
scores, labels = torch.max(labels,dim=-1)

the labels will be all zero right. when i tried for a different dataset with 3 classes,the labels are still zero since we are applying .view(-1,1) in first step. Any solutions?

**Comment by creotiv** [comment]
You are right I was not very clear here.
in view there should be .view(-1, classes), I just replaced it by 1 because in the current case there was only one class.  So it becomes:
`labels = res[:,:,boxes*5:].repeat((1,1,boxes)).view(-1,num_classes)`

My mistake, sorry.

**Comment by akashprakas** [comment]
Thanks :)
